export const fields = [
  'id',
  'name',
  { name: 'active', type: 'boolean' },
  'company_id',
  'uid',
  'captive_portal_id',
  // 'address_line_1',
  // 'address_line_2',
  // 'province_or_state',
  // 'city',
  // 'country',
  // 'lat',
  // 'lon',
]
